# This is a config for E2B sandbox template.
# You can use template ID (udjwa69l8y04zple73hf) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("udjwa69l8y04zple73hf") # Sync sandbox
# sandbox = await AsyncSandbox.create("udjwa69l8y04zple73hf") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('udjwa69l8y04zple73hf')

team_id = "2eddf308-a425-4045-98b3-aee4b7207ad3"
dockerfile = "e2b.Dockerfile"
template_id = "udjwa69l8y04zple73hf"
