# This is a config for E2B sandbox template.
# You can use template ID (2bx84fhk7iomwzrwqg9c) or template name (vibe-nextjs-ewebstore3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-ewebstore3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-ewebstore3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-ewebstore3')

team_id = "c1bfc10b-bdf0-4d71-8577-80281177d0f1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-ewebstore3"
template_id = "2bx84fhk7iomwzrwqg9c"
